# Generated by Django 5.1.4 on 2024-12-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_question_correct_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='skipped_questions',
            field=models.ManyToManyField(blank=True, related_name='skipped_sessions', to='quiz.question'),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='visited_questions',
            field=models.ManyToManyField(blank=True, related_name='visited_sessions', to='quiz.question'),
        ),
    ]
